import streamlit as st
from openai import OpenAI
from pydantic import BaseModel
from typing import Optional, List, Tuple, Any
import asyncio
import io

from agents import Agent, Runner, function_tool, trace, handoff

client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])


### TOOLS

### AGENTS

class ChartAgentFinalOutput(BaseModel):
    visualization_needed: bool
    comment: str
    code_block: str

data_vizualization_agent = Agent(
    name="data_vizualization_agent",
    instructions=("""
    You are a Data Visualization Agent. Your task is to:

    1. Analyze the structure of a pandas DataFrame based on its .info() output.
        
    2. First, decide if a visualization is appropriate to visualize this data. If not, explain briefly why a visualization may not be meaningful or suggest alternative summaries (e.g., a table, text summary, etc.).

    3. If a visualization is appropriate, determine the most suitable visualization type from the following options:
    - `st.area_chart`
    - `st.bar_chart`
    - `st.line_chart`
    - `st.scatter_chart`
    - `st.map`

    Use these guidelines:
    Use `line_chart` or `area_chart` when the data involves a continuous numerical variable over time, index, or ordered categories.
    Use `bar_chart` when comparing categorical data against numerical values.
    Use `scatter_chart` to explore relationships between two numerical fields.
    Use `map` to visualize geographical data points based on latitude and longitude coordinates.

    If the dataset lacks sufficient numeric or structured categorical data, or the sample size is too small, a visualization may not be helpful.

    4. Once the visualization type is selected, generate the Streamlit Python code for it, using the most logical columns as:
    - x (usually categorical or ordered)
    - y (numeric)
    - and optionally color or size if relevant.

    Assume the DataFrame is already named df. Include only the relevant arguments in the chart function. Output only the code block.

    ### Example Input
                    
    Index: 9 entries, 0 to 8  
    Data columns (total 4 columns):  
    #   Column  Non-Null Count  Dtype  
    ---  ------  --------------  -----  
    0   ID      9 non-null      int64  
    1   Name    9 non-null      object  
    2   Marks   9 non-null      int64  
    3   Grade   9 non-null      object  
    dtypes: int64(2), object(2)  

    ## df sample
    |    |   ID | Name   |   Marks | Grade   |
    |---:|-----:|:-------|--------:|:--------|
    |  0 |   23 | Ram    |      89 | B       |
    |  1 |   43 | Deep   |      97 | A       |
    |  2 |   12 | Yash   |      45 | F       |
    |  3 |   13 | Aman   |      78 | C       |
    |  4 |   67 | Arjun  |      56 | E       |

    ### Example Output
    st.bar_chart(data=df, x="Name", y="Marks", x_label="Student", y_label="Marks", use_container_width=True)
    """
    ), 
    # model="gpt-4o",
    model="gpt-4.1",
    output_type= ChartAgentFinalOutput,
)

async def run_chart_generator_agents(user_input: str, df_info: str) -> ChartAgentFinalOutput:
    """
    Generate appropriate chart visualization code based on DataFrame structure and user context.
    
    Args:
        user_input: Natural language description of what the user wants to visualize
        df_info: DataFrame information string containing schema and sample data
        
    Returns:
        ChartAgentFinalOutput: Contains chart code, feasibility decision, and explanatory message
    """

    context = f"User: {user_input}\n\n# DataFrame Info \n{df_info}"

    print(context)


    # Run the SME agent to analyze the request and extract context
    chart_result = await Runner.run(data_vizualization_agent, context)


    if not chart_result.final_output.chart_needed:
        print("SME Agent Comment:", chart_result.final_output.comment)

    # Print the structured context generated by the SME agent
    print("\nChart Agent:")
    print(chart_result.final_output)

    return chart_result.final_output

if __name__ == "__main__":



    user_input = "Show me the grades for my highschool class"

    import pandas as pd

    # dictionary of data
    dct = {'ID': {0: 23, 1: 43, 2: 12, 3: 13, 
                4: 67, 5: 89, 6: 90, 7: 56, 
                8: 34}, 
        'Name': {0: 'Ram', 1: 'Deep', 2: 'Yash',
                    3: 'Aman', 4: 'Arjun', 5: 'Aditya',
                    6: 'Divya', 7: 'Chalsea',
                    8: 'Akash' }, 
        'Marks': {0: 89, 1: 97, 2: 45, 3: 78,
                    4: 56, 5: 76, 6: 100, 7: 87,
                    8: 81}, 
        'Grade': {0: 'B', 1: 'A', 2: 'F', 3: 'C',
                    4: 'E', 5: 'C', 6: 'A', 7: 'B',
                    8: 'B'}
        }

    # forming dataframe and printing
    df = pd.DataFrame(dct)
    # print(df.info())

    buffer = io.StringIO()
    df.info(buf=buffer)
    df_info_str = buffer.getvalue()

    df_info_str += f"\n## df sample\n {df.head().to_markdown()}"

    print(df_info_str)

    with trace("Chart Agent"):
        asyncio.run(run_chart_generator_agents(user_input,df_info_str))